name: phan
on: pull_request

jobs:
  phan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer, cs2pr, phan
          coverage: none
      - name: Composer install
        run: composer install
      - name: Check Phan
        run: phan --no-progress-bar -m checkstyle | cs2pr
