name: phpstan
on: pull_request

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer, phpstan
          coverage: none
      - name: Composer install
        run: composer install
      - name: Check PHPstan
        run: phpstan analyse --error-format=github