name: psalm
on: pull_request

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer, psalm
          coverage: none
      - name: Composer install
        run: composer install
      - name: Check Psalm
        run: psalm --output-format=github
